name    'shaftoe-syslog_ng'
version '0.1.0'
source 'https://github.com/shaftoe/puppet-syslog_ng'
author 'shaftoe'
license 'Apache License, Version 2.0'
summary 'syslog-ng'
description 'Puppet module to manage syslog-ng'
project_page 'https://github.com/shaftoe/puppet-syslog_ng'
